name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@c4f70287fc37c43b14b30b407224bbbc8e8c6327
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /home/v18075636/0915
            git pull
            docker compose up -d --build
